### ISSUE TITLE
side effect in render phase

### ISSUE THREAD

**Issue by csr632** [react-spring/jotai#25]
https://github.com/react-spring/jotai/blob/eeeb7c1d9c947105befeb5e1ada28f4aa24db89c/src/useAtom.ts#L32

The callback of `useContextSelector` called in render phase. So I think this line is a side effect in render phase.

**Comment by dai-shi** [comment]
This line is actually OK, because we throw the promise anyway.
But, that's a good point. We are told that render must be pure. However, if we take the Fetch-on-Render approach and throw a promise, we need to mutate a state somewhere (= side effect), otherwise when a promise resolves it doesn't get the new state (= keep loading).

If we don't have async, the implementation would be much simplified.
It's the async and suspense that is complicated.
We don't have any best practices yet. Let me know if you experiment something or find a good pattern.

**Comment by dai-shi** [comment]
Closing this. I'd definitely revisit this once CM/Suspense lands and we understand the best practices.
Feel free to reopen for further discussions.

**Comment by dai-shi** [comment]
https://recoiljs.org/blog/2020/09/15/0.0.11-released/
So, it looks like recoil stores their state outside react...
We should probably follow react-query/swr pattern.
For async read operation, it should probably be fine. For async write, we might need to re-implement with effect chaining...

**Comment by dai-shi** [comment]
We fixed the async write in the latest version (v0.6.1).
Now, we should be able to follow the rule: https://gist.github.com/sebmarkbage/75f0838967cd003cd7f9ab938eb1958f
